### PR TITLE
add backup dump with mathsoc positions

### PR DESCRIPTION
**Pull request by alexgomez54**
issue #45

this is a first stab at the dump. i filled it with info for positions from the current mathsoc website, and dumped to a backup of the sqlite3 db. is this on the right track?

### CODE REVIEW

**Comment by tristan-potter** [comment]
how did you generate this? Did you know there is a manage.py command to dump data as JSON?

**Comment by alexgomez54** [comment]
Added in the admin gui, then used a sqlite3 command to dump to this.

didn't know, thx. this one can also be used to populate a new db using a similar sql command. is the json one better?

**Comment by tristan-potter** [comment]
I think the JSON one is probably better (more standard, we might change DB techs)

**Comment by alexgomez54** [comment]
Ok. Up as JSON. Let me know what you think.

**Pull request merged**
